### ISSUE TITLE
Not providing ident users blocks access

### ISSUE THREAD

**Issue by dw250304** [tewarid/node-tcp-proxy#15]
If you launch tcpproxy from the command line with no "-i" flag included, tcpproxy blocks all access.

Looking through source, it seems like this is not supposed to happen and instead all users should be allowed access.

![image](https://user-images.githubusercontent.com/66745357/93538846-2185b500-f91d-11ea-9826-35048c5b424c.png)

In the example above, the message "Allow all users" should probably be shown according to line 57 of tcp-proxy.js in https://github.com/tewarid/node-tcp-proxy/commit/9520b540ce7f6069dfb65963586ed76b0cb15616

**Comment by tewarid** [comment]
I noticed that it happens with v0.0.16 and pushed an update. The latest v0.0.17 should not have this issue.

**Comment by tewarid** [comment]
@dw250304 if you're happy with the fix, could you please close this issue. Thanks!

**Comment by dw250304** [comment]
Hey @tewarid sorry for the delay in reply. This is still happening on v0.0.17. I am using node/npm on Windows 10.

![image](https://user-images.githubusercontent.com/66745357/94437689-1b3cd780-016c-11eb-8c83-80303980195c.png)

**Comment by tewarid** [comment]
@dw250304 Should work now. Thanks!
