### ISSUE TITLE
Addition of CORS headers

### ISSUE THREAD

**Issue by izahoor-vwks** [tewarid/node-tcp-proxy#2]
Hi,

First of all thanks for providing a clean cli based proxy.
Secondly, can you please guide how we can enable CORS headers to each request that pass through this proxy server. 

Something similar to below:

```
// Set CORS headers
	res.setHeader('Access-Control-Allow-Origin', '*');
	res.setHeader('Access-Control-Request-Method', '*');
	res.setHeader('Access-Control-Allow-Methods', 'OPTIONS, GET');
	res.setHeader('Access-Control-Allow-Headers', '*');
	if ( req.method === 'OPTIONS' ) {
		res.writeHead(200);
		res.end();
		return;
	}
```

It would be a nice additional feature to use that as CLI argument.

Thanks.

**Comment by tewarid** [comment]
This is a simple pass-through proxy at the TCP level. It does not know anything about protocols layered over TCP such as the HTTP protocol. Maybe you're looking for a HTTP forward/reverse proxy?

**Comment by izahoor-vwks** [comment]
Ohh sorry. I didn't realize that. 

Am I correct in understanding that tcp-proxy will not modify any of HTTP headers if an HTTP REST call is passed through this proxy.

Regards

**Comment by tewarid** [comment]
Yes, your understanding is correct. It will pass through everything without touching it.

**Comment by izahoor-vwks** [comment]
Thanks for your help and a helpful utility. 
You can close the issue.
