### ISSUE TITLE
Support for key and cert tls options in server

### ISSUE THREAD

**Issue by tomelic** [tewarid/node-tcp-proxy#20]
Hi,
Using the node-tcp-proxy as a library (e.g, using the https->https example) the following options are used for the TLS server:

```
    this.options = Object.assign({
        quiet: false,
        pfx: require.resolve('./cert.pfx'),
        passphrase: 'abcd',
        rejectUnauthorized: true,
        identUsers: []
    }, options);
```

It would be nice to be able to use a CA self-signed server and key certificate as follows:
```
    this.options = Object.assign({
        quiet: false,
        cert: require.resolve('./server.key'), // <--- THIS
        key: require.resolve('./server.crt'),  // <--- AND THIS
        rejectUnauthorized: true,
        identUsers: []
    }, options)
```

I tried adding it to `node_modules/node-tcp-proxy/tcp-proxy.js` myself, but expectedly encountered errors such as:
```
internal/fs/utils.js:525
    throw new ERR_INVALID_ARG_TYPE(propName, ['string', 'Buffer', 'URL'], path);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type undefined

```

or file not found (when placed in same directory as the .pfx from the original example)
```
Error: ENOENT: no such file or directory, open './server.key'
```

I think it could be nice to add support for this use case as well 😉

**Comment by tewarid** [comment]
Are you trying to pin root cert of self-signed certificate used by service? A quick solution that wouldn't require changing the proxy would be to use [NODE_EXTRA_CA_CERTS environment variable](https://stackoverflow.com/questions/53543745/node-js-ssl-pinning-with-self-signed-certificate). It is a valid use case though :+1:.

**Comment by tomelic** [comment]
Thanks for prompt response, and no I'm not trying to pin a self-signed certificate.

I want to use a server certificate signed with my fake CA, and have proxy users install the CA cert on their different devices.

This is so that when a HTTPS requiring client (browser, phone, etc.) will recognize the proxy as tls negotiable

**Comment by tewarid** [comment]
The intention of the pfx option is to provide a self-signed certificate. I suppose you want to provide a PEM encoded cert (.pem or .key file) instead? How will clients discover the .crt file?

**Comment by tomelic** [comment]
Yeah exactly
And the clients in this scenario will have the root CA installed at trusted root CA authorities, and since the .crt file will be signed with the trusted CA, it will pose as secure.
the .crt file will be included in your library or embedded somewhere, same as the pfx

**Comment by tewarid** [comment]
You can convert certs in pem format to pfx using openssl, if that is an option

```bash
openssl pkcs12 -inkey server.key -in server.crt -export -out server.pfx -passout pass:foobar
```

Change `foobar` to any password you want to use.
