### ISSUE TITLE
How to forward TCP?

### ISSUE THREAD

**Issue by algj** [tewarid/node-tcp-proxy#21]
I know this is a stupid question, but I can't wrap my head around this module.

I have server and client that both work on localhost:2000.
I want to secure it with a passphrase (no TLS needed).

`server :2000 <- tcpproxy :2001 <- internet <- tcpproxy :2001 <- client :2000`

What options should I use on command line?

Thanks.

**Comment by tewarid** [comment]
Not a stupid question at all, really.

This module does not provide support for adding authentication to a service. 

You can, however, use the extension mechanism, to intercept data when it arrives and ensure it starts with a passphrase of your choosing, that you can strip from the data before sending it along to your service.

I can see now that an event that informs when the client, or service, has disconnected could clearly be useful to cleanup state.

**Comment by algj** [comment]
I did find your tcp-relay-proxy, I guess this will be useful to me!
Thank you
