### ISSUE TITLE
how can I block some traffic and return data to client 

### ISSUE THREAD

**Issue by naimimohammad** [tewarid/node-tcp-proxy#25]
I want to block some upstream data and return data without data reaches to downstream

**Comment by tewarid** [comment]
Please take a look at the logger example to see how to alter upstream or downstream data.

https://github.com/tewarid/node-tcp-proxy/blob/6e897db610ae6ee383a41af733d3ab05e7a0aa83/examples/logger/index.js#L20

**Comment by naimimohammad** [comment]
could you explain more?
for example, I use proxy to connect HTTP client to HTTP server , and if client send some data (for example data size is more than some ) I don't pass this data to HTTP server and return custom data to HTTP client ,
and how can I alter upstream and downstream?
remove them? 
for example I want to return `data` as `{hello:true}` if data.length > 2000 and didn't allow to pass this data to HTTP server
