### ISSUE TITLE
logs "Allow all users" to console when using the programmatic interface

### ISSUE THREAD

**Issue by jedwards1211** [tewarid/node-tcp-proxy#28]
Took me awhile to figure out it was coming from this package...

**Comment by tewarid** [comment]
Please try using the quiet option.

**Comment by jedwards1211** [comment]
@tewarid it logs to the console when I'm using the Node.js API.  It makes sense for the CLI to log by default, but the Node.js API should not.

**Comment by jedwards1211** [comment]
@tewarid at the very least, if you want the programmatic interface to log warnings by default, they ought to be prefixed with `[node-tcp-proxy]` so that it's clear where the warnings came from.
