### ISSUE TITLE
Is it possible to rewrite originator IP address with proxy's?

### ISSUE THREAD

**Issue by AxelHeathnet** [tewarid/node-tcp-proxy#35]
I'm using node-tcp-proxy to reach a private endpoint, estabilishing a bastion host.

Problem is that it seems the proxy also substitutes the proxy request IP with the source host request IP. 
As the end service only allows calls from the bastion host the connection fails. 
Is it possible to give an option to not put forward the originator's address?

**Comment by tewarid** [comment]
Can you please clarify how your networking is setup. node-tcp-proxy operates at [layer 4](https://www.haproxy.com/blog/layer-4-and-layer-7-proxy-mode/) so it depends on network routes being setup appropriately on the proxy host. It seems your public network is able to see your private network thus exposing your private/service host directly to the world.
