### ISSUE TITLE
Load Balancing in an app

### ISSUE THREAD

**Issue by Yomanz** [tewarid/node-tcp-proxy#7]
Hey thanks for the quick update after my last issue, I noticed you updated the command on how to do the load balancing but not the app example, it would be greatly appreciated if you could :)

**Comment by tewarid** [comment]
If you're referring to the example in the readme file, I did update it, perhaps it isn't clear enough?

**Comment by Yomanz** [comment]
Perhaps it's me being odd but I am referring to:
https://github.com/tewarid/node-tcp-proxy#programming-interface
